// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8U3NBLV_9dx0hGzkWwO09jnu5luq_0P0',
    appId: '1:859810132732:web:0c55f7ba0c7eaec600dd79',
    messagingSenderId: '859810132732',
    projectId: 'campus-event-remainder',
    authDomain: 'campus-event-remainder.firebaseapp.com',
    storageBucket: 'campus-event-remainder.firebasestorage.app',
    measurementId: 'G-5XYV45XXTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoBV6PDRbhbV_D5Rkb-0VgrzqNhJ12jw',
    appId: '1:859810132732:android:47cf5498f25bcd3400dd79',
    messagingSenderId: '859810132732',
    projectId: 'campus-event-remainder',
    storageBucket: 'campus-event-remainder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKciShdiGACqWUpD2SPydbCEjvS8wnoWg',
    appId: '1:859810132732:ios:a6af764f54746f5400dd79',
    messagingSenderId: '859810132732',
    projectId: 'campus-event-remainder',
    storageBucket: 'campus-event-remainder.firebasestorage.app',
    iosBundleId: 'com.example.eventReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKciShdiGACqWUpD2SPydbCEjvS8wnoWg',
    appId: '1:859810132732:ios:a6af764f54746f5400dd79',
    messagingSenderId: '859810132732',
    projectId: 'campus-event-remainder',
    storageBucket: 'campus-event-remainder.firebasestorage.app',
    iosBundleId: 'com.example.eventReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8U3NBLV_9dx0hGzkWwO09jnu5luq_0P0',
    appId: '1:859810132732:web:a73f6d97542b7f2600dd79',
    messagingSenderId: '859810132732',
    projectId: 'campus-event-remainder',
    authDomain: 'campus-event-remainder.firebaseapp.com',
    storageBucket: 'campus-event-remainder.firebasestorage.app',
    measurementId: 'G-HMK088HF9Q',
  );
}
